using Godot;

namespace TerraBrush;

internal static class StringNames {
    public static readonly StringName HeightmapTextures = "HeightmapTextures";
    public static readonly StringName ZonesSize = "ZonesSize";
    public static readonly StringName NumberOfZones = "NumberOfZones";
    public static readonly StringName ZonesMap = "ZonesMap";
    public static readonly StringName GlobalPosition = "GlobalPosition";
    public static readonly StringName Splatmaps = "Splatmaps";
    public static readonly StringName Textures = "Textures";
    public static readonly StringName NumberOfTextures = "NumberOfTextures";
    public static readonly StringName TextureDetail = "TextureDetail";
    public static readonly StringName FoliageTextures = "FoliageTextures";
    public static readonly StringName MeshScale = "MeshScale";
    public static readonly StringName WindStrength = "WindStrength";
    public static readonly StringName WaterTextures = "WaterTextures";
    public static readonly StringName WaterFactor = "WaterFactor";
    public static readonly StringName NoiseTexture = "NoiseTexture";
    public static readonly StringName MaximumDistance = "MaximumDistance";
    public static readonly StringName SnowTextures = "SnowTextures";
    public static readonly StringName SnowFactor = "SnowFactor";
    public static readonly StringName SnowInnerOffset = "SnowInnerOffset";
    public static readonly StringName SnowColorTexture = "SnowColorTexture";
    public static readonly StringName SnowColorNormal = "SnowColorNormal";
    public static readonly StringName SnowColorRoughness = "SnowColorRoughness";
    public static readonly StringName SnowColorDetail = "SnowColorDetail";
    public static readonly StringName Noise = "Noise";
    public static readonly StringName NoiseFactor = "NoiseFactor";
    public static readonly StringName Metallic = "Metallic";
    public static readonly StringName NearestFilter = "NearestFilter";
    public static readonly StringName TexturesDetail = "TexturesDetail";
    public static readonly StringName HasNormalTextures = "HasNormalTextures";
    public static readonly StringName HasRoughnessTextures = "HasRoughnessTextures";
    public static readonly StringName HasHeightTextures = "HasHeightTextures";
    public static readonly StringName UseAntitile = "UseAntitile";
    public static readonly StringName BlendFactor = "BlendFactor";
    public static readonly StringName WaterInnerOffset = "WaterInnerOffset";
    public static readonly StringName WaterColor = "WaterColor";
    public static readonly StringName FresnelColor = "FresnelColor";
    public static readonly StringName Roughness = "Roughness";
    public static readonly StringName NormalMap = "NormalMap";
    public static readonly StringName NormalMap2 = "NormalMap2";
    public static readonly StringName TimeScale = "TimeScale";
    public static readonly StringName Strength = "Strength";
    public static readonly StringName Wave = "Wave";
    public static readonly StringName NoiseScale = "NoiseScale";
    public static readonly StringName HeightScale = "HeightScale";
    public static readonly StringName ColorDeep = "ColorDeep";
    public static readonly StringName ColorShallow = "ColorShallow";
    public static readonly StringName BeersLaw = "BeersLaw";
    public static readonly StringName DepthOffset = "DepthOffset";
    public static readonly StringName EdgeScale = "EdgeScale";
    public static readonly StringName Near = "Near";
    public static readonly StringName Far = "Far";
    public static readonly StringName EdgeColor = "EdgeColor";
    public static readonly StringName SetAnglePointContainer = "SetAnglePointContainer";
}
