#ifndef ENUMS_H
#define ENUMS_H

#include <godot_cpp/core/class_db.hpp>

using namespace godot;

enum FoliageStrategy : int {
    FOLIAGESTRATEGY_MULTIMESH = 1,
    FOLIAGESTRATEGY_GPUPARTICLE = 2
};
VARIANT_ENUM_CAST(FoliageStrategy);

enum TerrainToolType {
    TERRAINTOOLTYPE_NONE = 0,
    TERRAINTOOLTYPE_TERRAINADD = 1,
    TERRAINTOOLTYPE_TERRAINREMOVE = 2,
    TERRAINTOOLTYPE_TERRAINSMOOTH = 3,
    TERRAINTOOLTYPE_TERRAINFLATTEN = 4,
    TERRAINTOOLTYPE_TERRAINSETHEIGHT = 5,
    TERRAINTOOLTYPE_TERRAINSETANGLE = 19,
    TERRAINTOOLTYPE_PAINT = 6,
    TERRAINTOOLTYPE_FOLIAGEADD = 7,
    TERRAINTOOLTYPE_FOLIAGEREMOVE = 8,
    TERRAINTOOLTYPE_OBJECTADD = 9,
    TERRAINTOOLTYPE_OBJECTREMOVE = 10,
    TERRAINTOOLTYPE_WATERADD = 11,
    TERRAINTOOLTYPE_WATERREMOVE = 12,
    TERRAINTOOLTYPE_WATERFLOWADD = 13,
    TERRAINTOOLTYPE_WATERFLOWREMOVE = 14,
    TERRAINTOOLTYPE_SNOWADD = 15,
    TERRAINTOOLTYPE_SNOWREMOVE = 16,
    TERRAINTOOLTYPE_HOLEADD = 17,
    TERRAINTOOLTYPE_HOLEREMOVE = 18,
    TERRAINTOOLTYPE_LOCKADD = 20,
    TERRAINTOOLTYPE_LOCKREMOVE = 21,
    TERRAINTOOLTYPE_METAINFOADD = 22,
    TERRAINTOOLTYPE_METAINFOREMOVE = 23,
};
VARIANT_ENUM_CAST(TerrainToolType);

enum ObjectStrategy {
    OBJECTSTRATEGY_PACKEDSCENES = 1,
    OBJECTSTRATEGY_OCTREEMULTIMESHES = 2
};
VARIANT_ENUM_CAST(ObjectStrategy);

enum ObjectLoadingStrategy {
    OBJECTLOADINGSTRATEGY_THREADEDINEDITORONLY = 1,
    OBJECTLOADINGSTRATEGY_THREADED = 2,
    OBJECTLOADINGSTRATEGY_NOTTHREADED = 3
};
VARIANT_ENUM_CAST(ObjectLoadingStrategy);

enum AlphaChannelUsage {
    ALPHACHANNELUSAGE_NONE = 0,
    ALPHACHANNELUSAGE_ROUGHNESS = 1,
    ALPHACHANNELUSAGE_HEIGHT = 2
};
VARIANT_ENUM_CAST(AlphaChannelUsage);
#endif