#include "string_names.h"

using namespace godot;

StringName StringNames::HeightmapTextures() { return "HeightmapTextures"; }
StringName StringNames::ZonesSize() { return "ZonesSize"; }
StringName StringNames::NumberOfZones() { return "NumberOfZones"; }
StringName StringNames::ZonesMap() { return "ZonesMap"; }
StringName StringNames::GlobalPosition() { return "GlobalPosition"; }
StringName StringNames::Splatmaps() { return "Splatmaps"; }
StringName StringNames::Textures() { return "Textures"; }
StringName StringNames::NumberOfTextures() { return "NumberOfTextures"; }
StringName StringNames::TextureDetail() { return "TextureDetail"; }
StringName StringNames::FoliageTextures() { return "FoliageTextures"; }
StringName StringNames::MeshScale() { return "MeshScale"; }
StringName StringNames::WindStrength() { return "WindStrength"; }
StringName StringNames::WaterTextures() { return "WaterTextures"; }
StringName StringNames::WaterFactor() { return "WaterFactor"; }
StringName StringNames::NoiseTexture() { return "NoiseTexture"; }
StringName StringNames::MaximumDistance() { return "MaximumDistance"; }
StringName StringNames::SnowTextures() { return "SnowTextures"; }
StringName StringNames::SnowFactor() { return "SnowFactor"; }
StringName StringNames::SnowInnerOffset() { return "SnowInnerOffset"; }
StringName StringNames::SnowColorTexture() { return "SnowColorTexture"; }
StringName StringNames::SnowColorNormal() { return "SnowColorNormal"; }
StringName StringNames::SnowColorRoughness() { return "SnowColorRoughness"; }
StringName StringNames::SnowColorDetail() { return "SnowColorDetail"; }
StringName StringNames::Noise() { return "Noise"; }
StringName StringNames::NoiseFactor() { return "NoiseFactor"; }
StringName StringNames::Metallic() { return "Metallic"; }
StringName StringNames::NearestFilter() { return "NearestFilter"; }
StringName StringNames::TexturesDetail() { return "TexturesDetail"; }
StringName StringNames::HasNormalTextures() { return "HasNormalTextures"; }
StringName StringNames::HasRoughnessTextures() { return "HasRoughnessTextures"; }
StringName StringNames::HasHeightTextures() { return "HasHeightTextures"; }
StringName StringNames::UseAntitile() { return "UseAntitile"; }
StringName StringNames::BlendFactor() { return "BlendFactor"; }
StringName StringNames::WaterInnerOffset() { return "WaterInnerOffset"; }
StringName StringNames::WaterColor() { return "WaterColor"; }
StringName StringNames::FresnelColor() { return "FresnelColor"; }
StringName StringNames::Roughness() { return "Roughness"; }
StringName StringNames::NormalMap() { return "NormalMap"; }
StringName StringNames::NormalMap2() { return "NormalMap2"; }
StringName StringNames::TimeScale() { return "TimeScale"; }
StringName StringNames::Strength() { return "Strength"; }
StringName StringNames::Wave() { return "Wave"; }
StringName StringNames::NoiseScale() { return "NoiseScale"; }
StringName StringNames::HeightScale() { return "HeightScale"; }
StringName StringNames::ColorDeep() { return "ColorDeep"; }
StringName StringNames::ColorShallow() { return "ColorShallow"; }
StringName StringNames::BeersLaw() { return "BeersLaw"; }
StringName StringNames::DepthOffset() { return "DepthOffset"; }
StringName StringNames::EdgeScale() { return "EdgeScale"; }
StringName StringNames::Near() { return "Near"; }
StringName StringNames::Far() { return "Far"; }
StringName StringNames::EdgeColor() { return "EdgeColor"; }
StringName StringNames::SetAnglePointContainer() { return "SetAnglePointContainer"; }
StringName StringNames::InitialCellWidth() { return "InitialCellWidth"; }
StringName StringNames::LODRowsPerLevel() { return "LODRowsPerLevel"; }
StringName StringNames::LODLevels() { return "LODLevels"; }
StringName StringNames::FoliageAlbedo() { return "FoliageAlbedo"; }
StringName StringNames::FoliageAlbedoTextures() { return "FoliageAlbedoTextures"; }
StringName StringNames::FoliageAlbedoTexturesNearest() { return "FoliageAlbedoTexturesNearest"; }
StringName StringNames::UseGroundColor() { return "UseGroundColor"; }
StringName StringNames::FoliageNumberOfTexture() { return "FoliageNumberOfTexture"; }
StringName StringNames::UseBrushScale() { return "UseBrushScale"; }
StringName StringNames::ScaleNoiseTexture() { return "ScaleNoiseTexture"; }
StringName StringNames::RandomPlacementRange() { return "RandomPlacementRange"; }
StringName StringNames::InvertedZ() { return "InvertedZ"; }
StringName StringNames::TerrainLoaded() { return "TerrainLoaded"; }
StringName StringNames::LockTextures() { return "LockTextures"; }
StringName StringNames::ApplyLockTextures() { return "ApplyLockTextures"; }
StringName StringNames::ApplyOnTextureIndexes() { return "ApplyOnTextureIndexes"; }
StringName StringNames::NumberOfTexturesToApplyOn() { return "NumberOfTexturesToApplyOn"; }
StringName StringNames::AlbedoAlphaChannelUsage() { return "AlbedoAlphaChannelUsage"; }
StringName StringNames::NormalAlphaChannelUsage() { return "NormalAlphaChannelUsage"; }
StringName StringNames::OffsetPosition() { return "OffsetPosition"; }
StringName StringNames::Resolution() { return "Resolution"; }
StringName StringNames::Triplanar() { return "Triplanar"; }
StringName StringNames::TexturesTriplanar() { return "TexturesTriplanar"; }
StringName StringNames::UseSharpTransitions() { return "UseSharpTransitions"; }
StringName StringNames::ApplyMetaInfoTextures() { return "ApplyMetaInfoTextures"; }
StringName StringNames::MetaInfoTextures() { return "MetaInfoTextures"; }
StringName StringNames::MetaInfoColors() { return "MetaInfoColors"; }